### ISSUE TITLE
Add detailed Installation Instructions to README

### ISSUE THREAD

**Issue by szsdk** [OrangeX4/mitex#17]
I am genuinely impressed with potential of this project and excited about the possibilities it offers. However, I've encountered a bit of a roadblock. As a new user, I'm unsure about the installation process, as the current README file doesn't include an installation section. This has made it challenging for me to get started with the project.

Could you please consider adding an installation guide to the README?

**Comment by Myriad-Dreamin** [comment]
The regular way to install it is just including `@preview/mitex:0.0.0` once after it gets published, which is easy.

Also it may not be a good idea to including a "install it locally" section in README.md, because some users were ever confusing by similar section in cetz's README.md, and got stuck on failing to execute installation instructions. Considering that, I feel cloning and using package is for contributors to MiTeX or advanced users. It is still okay to have a CONTRIBUTING.md and contains above content.

**Comment by szsdk** [comment]
Just test it and it looks amazing. Please feel free to close this issue.
